import type { Metadata } from "next";
import "@/styles/globals.css";
import fonts from "@/data/fonts.data";
import Navbar from "@/component/Navbar";

export const metadata: Metadata = {
  title: "Art Pill Recreation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fonts} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
