import type { Metadata } from "next";
import "@/styles/globals.css";
import fonts from "@/data/fonts.data";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fonts} antialiased`}>{children}</body>
    </html>
  );
}
